on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: tests
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "Windows-latest"]
        python: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install
      - name: Lint
        run: ./scripts/lint.sh
      - name: Test
        run: ./scripts/test.sh
      - name: Build
        run: |
          poetry build
          python -m pip install dist/gitpkg-*.whl --force-reinstall
          which git-pkg
